<style type='text/css'>
 
	  
table.dtable td{
border-left: 1px solid #6B78A9; 
border-top: 1px solid #6B78A9; 

}
.dtable{
margin: 5px 0 0 0; 
padding: 5px 5px 5px 5px;
border: 1px solid #6B78A9; 
background-color: #F7F7F4;
}
.formfield{
border-bottom:1px dotted #6B78A9;
}

	
label {
	display:block;
	font-weight:bold;
	margin:50px 0;
	}
	
input {
	margin-bottom: 1px;
	border: 1px solid #ccc;
	font-family: Verdana,Helvetica,Sans-Serif;
	font-size: 12px;
	color:#777;
	background-color:#fff;
	}
	
textarea {
	width:300px;
	padding:2px;
	font-family: Verdana,Helvetica,Sans-Serif;
	height:70px;
	display:block;
	color:#777;
	border: 1px solid #ccc;
	}
	
select { 
	border:1px solid #ccc;
	margin-bottom: 2px;
	} 

option { 
	/*width: 200px;*/
	border:0px solid #ccc;   
	}

fieldset {
	padding: 1em;
	border:1px solid #CCC;
	background-color: #F7F7F7; 
	}
  
legend {
	margin-bottom: 8px;
	padding: 5px 5px 5px 5px;
	border:1px solid #CCC;
	background-color: #F7F7F4; 
	}

.editfield
{
border:1px solid red;
}

.editrow
{
border:1px solid red;
background-color: #9EC7A2; 
}

.dhead th
{
background-color: white; 
border:1px solid #F4EFDF;
}

a img {
	border: none;
}

.dleft
{
border-left:0px;
}


</style>
