<style type="text/css">
<!--
body
{
font-familiy:Aerial;
size:12pt;
}
	table.page_header 
	{
	width: 100%;
	border: 0px; 
	background-color: #F7F7F4; 
	border-bottom:1px solid #F7F7F4;
	padding: 2mm 
	}
	.page_table 
	{
	width: 100%;
	border: 1px solid black; 
	background-color: #F7F7F4; 
	}
	table.page_footer
	{
	width: 100%; 
	border: none; 
	background-color:white;
	border-top: solid 1px white;
	padding: 2mm
       
        }
	div.note {
	border: solid 1mm #F7F7F4;
	background-color: #F7F7F4; 
	padding: 2mm; 
	border-radius: 2px 2px;
	width: 100%;
	}
	h1 {
	text-align: center; 
	font-size: 2px;
	}
	h3 {
	text-align: center; 
	font-size: 1px;
	}

table.dtable td{
border-left: 1px solid #cfcfcfc; 
border-top: 1px solid #cfcfcfc; 
size:11pt;
}
.dtable{
border-right: 1px solid black;
border-bottom: 1px solid black;  
background-color:white ;
}
.dhead th
{
background-color: #F7F7F4; 
border-left:1px solid black;
border-top:1px solid black;
text-align:center;
}

LI.degree  { list-style-type: none }

-->
</style>
