<?php
    
    $config_file_default    = "config.default";    
    $config_file_directory  = "";	
    $config_file_name       = "config.inc.php";    
    $config_file_path       = $config_file_directory.$config_file_name;
    
    $application_name       = "PHP DataGrid";
    $application_start_file = "../index.php";
    
    $license_agreement_page = "";
    
    $sql_dump               = "../sql/db_dump.sql";
    
?>
